version: "3.2"
services:
  server:
    image: aslipatov/studentalcohol-server:latest
    restart: always
    container_name: code
    command : bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - db-net
    
  client:
    image: aslipatov/studentalcohol-client:latest
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - server
    networks:
      - db-net

networks:
  db-net:
    driver: bridge